name: Build

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'NOTICE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'NOTICE'
      - 'README.md'

jobs:
  cmake:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cxx: [g++, clang++]
    env:
      CXX: ${{matrix.cxx}}
      workflow_src_dir: ${{github.workspace}}
      workflow_build_dir: ${{github.workspace}}/build
      build_type: Release
    defaults:
      run:
        working-directory: ${{env.workflow_build_dir}}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Mkdir
      working-directory: ${{env.workflow_src_dir}}
      run: mkdir ${{env.workflow_build_dir}}

    - name: Configure
      run: cmake ${{env.workflow_src_dir}} -DCMAKE_BUILD_TYPE=${{env.build_type}}

    - name: Build
      run: cmake --build . --config ${{env.build_type}}
